WEBSOCKET_URL = "wss://ws.playerok.com/graphql"
WEBSOCKET_PROTOCOL = "graphql-transport-ws"
ACK_TIMEOUT = 15
HEARTBEAT_TIMEOUT = 30
RECONNECT_DELAY = 3
FRAME_SIZE_LIMIT = 1048576
HYDRATION_ATTEMPTS = 3
HYDRATION_DELAY = 2
MAX_WATCHED_REVIEWS = 400
MAX_CHAT_SUBSCRIPTIONS = 60
MAX_TRACKED_CHATS = 300
MAX_PARSED_MESSAGE_IDS = 20000
REVIEW_WATCH_SECONDS = 259200
SYSTEM_EVENT_ALIASES = {
    "OFFICIAL_ITEM_PAID": "ITEM_PAID",
    "ITEM_SENT_AUTOMATICALLY": "ITEM_SENT",
    "DEAL_CONFIRMED_AUTOMATICALLY": "DEAL_CONFIRMED",
    "DEAL_CONFIRMED_AFTER_PROBLEM": "DEAL_CONFIRMED",
}
STREAM_INIT_PAYLOAD = {
    "x-gql-op": "ws-subscription",
    "x-gql-path": "/chats/[id]",
    "x-timezone-offset": -180,
}
