from colorama import Fore
BUILD = '1.0.0'
C_PRIMARY = Fore.CYAN
C_SUCCESS = Fore.LIGHTGREEN_EX
C_WARNING = Fore.YELLOW
C_ERROR = Fore.LIGHTRED_EX
C_DIM = Fore.LIGHTBLACK_EX
C_TEXT = Fore.WHITE
C_BRIGHT = Fore.LIGHTWHITE_EX
C_HIGHLIGHT = Fore.LIGHTCYAN_EX
VERSION = BUILD
ACCENT_COLOR = C_PRIMARY
