
class CX:
    noop = 'noop'

    evt_back = 'cx_eb'
    dismiss = 'cx_xx'

    pl_tk = 'cx_01'
    pl_to = 'cx_02'
    pl_ua = 'cx_03'
    pl_px = 'cx_04'
    tg_px = 'cx_05'
    px0 = 'cx_06'
    tx0 = 'cx_07'

    wm_en = 'cx_08'
    wm_tx = 'cx_09'
    wm_vl = 'cx_0a'
    wm_pre = 'cx_0b'
    wm_pst = 'cx_0c'

    rs_sd = 'cx_0d'
    rs_ex = 'cx_0e'
    rs_all = 'cx_0f'
    rs_pol = 'cx_0g'
    rs_pol_iv = 'cx_0h'
    nv_rs = 'cx_0i'
    in_rs_kw = 'cx_0j'
    f_rs_txt = 'cx_0k'

    sh_en = 'cx_0l'
    sh_all = 'cx_0m'
    in_sh_kw = 'cx_0n'
    f_sh_txt = 'cx_0o'

    bm_en = 'cx_0p'
    bm_all = 'cx_0q'
    bm_iv = 'cx_0r'
    bm_go = 'cx_0s'
    bm_run = 'cx_0t'
    nv_bi = 'cx_0u'
    nv_bx = 'cx_0v'
    in_bm_i_kw = 'cx_0w'
    in_bm_x_kw = 'cx_0x'
    f_bm_i_txt = 'cx_0y'
    f_bm_x_txt = 'cx_0z'

    rd_en = 'cx_10'
    db_v = 'cx_11'

    lg_en = 'cx_12'
    lg_um = 'cx_13'
    lg_sy = 'cx_14'
    lg_dl = 'cx_15'
    lg_st = 'cx_16'
    lg_rv = 'cx_17'
    lg_sp = 'cx_18'
    lg_rs = 'cx_19'
    lg_bm = 'cx_1a'

    tpl_en = 'cx_1b'
    tpl_nid = 'cx_1c'
    tpl_tx = 'cx_1d'
    tpl_pg = 'cx_1e'
    tpl_dq = 'cx_1f'
    tpl_del = 'cx_1g'

    cc_en = 'cx_1h'
    cc_pg = 'cx_1i'
    cc_new = 'cx_1j'
    cc_ans = 'cx_1k'
    cc_dok = 'cx_1l'
    cc_del = 'cx_1m'

    ad_en = 'cx_1n'
    ad_pg = 'cx_1o'
    ad_kw_n = 'cx_1p'
    ad_kw_e = 'cx_1q'
    ad_msg = 'cx_1r'
    ad_pc = 'cx_1s'
    ad_g_add = 'cx_1t'
    ad_g_pg = 'cx_1u'
    ad_go = 'cx_1v'
    ad_dok = 'cx_1w'
    ad_del = 'cx_1x'

    log_mb = 'cx_1y'
    log_sn = 'cx_1z'

    lg_bt = 'cx_28'

    xt_pg = 'cx_20'
    xt_on = 'cx_21'
    xt_rf = 'cx_22'

    st_dq = 'cx_23'
    st_rst = 'cx_24'
    st_bk = 'cx_25'

    dl_rf = 'cx_26'
    dl_ok = 'cx_27'
