from colorama import Fore

BUILD = '2.0.0'
VERSION = BUILD
ACCENT_COLOR = Fore.CYAN
C_PRIMARY   = Fore.CYAN
C_SUCCESS   = Fore.LIGHTGREEN_EX
C_WARNING   = Fore.YELLOW
C_ERROR     = Fore.LIGHTRED_EX
C_DIM       = Fore.LIGHTBLACK_EX
C_TEXT      = Fore.WHITE
C_BRIGHT    = Fore.LIGHTWHITE_EX
C_HIGHLIGHT = Fore.LIGHTCYAN_EX
